### ISSUE TITLE
Grading

### ISSUE THREAD

**Issue by sachintha180** [ZeeFuzooly/review-page#1]
Hi - this is Sachintha from Teams Squared. Great work with your submission!

You've scored 40/50 for your submission. You have lost marks for:
- Lack of smooth animation for the faces' expression.
- Lack of divisions for the slider (i.e. wheel)
- The popup message (upon pressing the "Submit" button) not displaying the correct rating face (always shows the green "GOOD" smiley face)

**Comment by ZeeFuzooly** [comment]
Hi Sachintha,

Thank you for the feedback on my submission. I’m currently working on the
areas you mentioned:

• Adding smooth animations for the face expressions. • Implementing
divisions for the slider.
• Correcting the popup message to display the accurate rating face.


Due to time constraints, I wasn’t able to complete these parts initially.
Please let me know what the next steps are, including if there is a client
interview or any other upcoming stages in the process?


 Best regards,
 Ziran Fuzooly

**Comment by sachintha180** [comment]
Got it - if you have the time, please feel free to submit your final before Monday (12th). We're happy to take a look at it once again.

And regarding the next steps - Amresh will definitely get back to you via email. If there's any additional updates, I will get back to you as well. 

Best regards,
Sachintha.

**Comment by ZeeFuzooly** [comment]
Awesome, thank you so much!
